apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-b2-credentials
  namespace: batchsender
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: github-secrets
    kind: SecretStore
  target:
    name: loki-b2-credentials
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        key: B2_KEY_ID
    - secretKey: secret-access-key
      remoteRef:
        key: B2_APP_KEY
