---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: batchsender
spec:
  encryptedData:
    admin-password: AgBprdy/+qx/P9WuUwojrVE62ZPIiI4HllGSbw1fJtAOYEwCuTStIAr7CvV79tcV4cqX+95DRnwg6t2TA4inSQy+8VYNTijzYb3E+Gv7jhvTgaK019pQP7Gnq4oA7HvqA7XDUQtts5Yj6ZPt9fiPrqLdKwi5x69Xb+feYoX8g5ORlS5ynFOoHpR0I0H0TLNbtgh0fNlUdz8qm6s4lFxiFYy6LFr+UN9mrBx5SKrpVEjjtn8K38XYyMuZE+5nmIRs4q6HWit9tEzFjGqjWlsvOvtPsWEptOKQQ6FLpeGnBz+h2qYGVwqxhNXHwSXsnHzflE8EKtE8hV1m8yd+gMgJZebEUCEr/83UJC90VOsHZHrak1Poj7C4hJS1EzSz5B/Pskv/JN2YO3xIk6blxcdhS204SoumK5bQJZZ2x/9FQkApjRTmP6B6c/glPhdkXpq03HKzk6/GPuHGHxuNfHVX+4acexSZQw/qoV6HKK0Cn1qXgceNCTpC3qhcVDt5QThO3bkw9o0SCB96ennR6mzfocliWaV925ssfF4hZXW+KYwm1EbKj4kbMxhusxXxSZGp836q9nFuqzUyKPGiRGGTtML4XlWzZ5Oif0pk9gU+XQTrFBTBq3Z+zZzGAgafByibSd1n0PhEDdtEZX2Z1JIAEj7WW3hCbPP8Dg9IQI8OPXLbdhPSUVF56rA1FdwQ6vk2DUX3v3Qu2n1PyvmOt2wWVd4SeByYrfdkCaNxXXVDbCHJHHp0zNhS6lOdxEwM
    neon-db-password: AgAiVVRh6bywA9itnTf+1MfX47LXMnk6NpDSJ6fNiwGhkTK9laTzbU/81rVDkTJ6+bHWzgHDt1lGCJXuy+EhW6sF2M6wNgvnknVmOwI2cQkWiwxefL+2OpT5vxwD5e1GvD+j4YnKZkv/FuOehd1rOtpYOGSMboUh10PeQkEnyEq/2tD2dLyDW23KLmPdeVICrULMrNM7uas6vpM3SobJ9mXS4Ukg1ZQ7gTu/FgUusbSn0OdXesgZHklNnnyGFESp+U22C3diJmONFhrpmx33o//6x/gvWZFbJ49VEpUWd1RaZxZKgztMMJ0v7jmZZUkAB7BPhlzrBxKnXIBnBnPJt6NoeFEwxLveYAXFLIHkxDjt1VGjrmmBk5ft46+Y03Cviyy84Px8O+qd/jENZ1wdguJX1EwYhbRT0mrImJj6QAp77Fjge3nk9UCA67+h1lnFxdF8jHPO5dxFvtuiIgDj7UOBuFUOH7EkUHEeCEdmezUMbaT1bXYJByJh8SrdN/GW4R4d51/hir/uovHA1o/ojscKyP3IF7YSl+HCWTATAeZMezjX2CIw7bXHywa0VDzK/uGY+UjVX44Ry1V30/L9EpDZtQqraBrzM32rAEx2vnL7spenHaxUyGJ4/lx5Ueskmb2yZOZkbRfIwj3TGyh5RX8Xl98YrLPDAmxSGZ73Sf2xWC8OSdPffjANo5jowPkcY1ThmIf9K4sSzGHIWfwW12Hk
  template:
    metadata:
      name: grafana-secret
      namespace: batchsender
