---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: batchsender
spec:
  encryptedData:
    admin-password: AgAIddanqISB8lScP66JSVr8DL0KEBXc/t8i4opr2n2zraEOpddZkCYZ62COmZgg6jf2EVMnBMX4saE/AygSDVRE3IiGFVnsHxqh1zn+Ayn1uAiVBUlw2RRQ0YOhrLt32eMG01JnzZriu5omtcpUzyGZOWq+yw6LfXVI2+OKRuXztPQnSDuDln5C06pHrtupzcP7RG2v3J5duNQS7snvvbizeSdnxK9TrcqRfsoeVHH1crn00t8Q0EEXZr4Bjid+bbtMYQjp3cl3Yy4mKsbFsks2NsYGUBZSgqokVopFbHA0xGLd6CfEE7tqOa/u3AyyNK5WdOKq3OtKRPRnqnbBuRjXCb/UwpBMZR9r3c7N2gmOhurtGzYLRQzxXi2jQR9wnBMjda/bzGKT/NjXxI6fK5HwRNsVsjvtSRrTpQAwMnKLuv/i1qHGBuV+KOWQ0aqVcpjxtxpobtUTE9NLMDa1g5J5M1kvRIMWtJ6J3Jiv/LhLMKom/9io+zkPNQQvmZTcnWc/5iiVhLQeZx+dixX6aSfJ0aenweSuDQfBoqSd8zCU8ZnsYVQ6s0np4YNou15rmTNNz4vo/1N5hr5TMQ79NiPUqs56gRfmbGwzOIVSArVIpjmqaEpXBhn584+9HLbzBzcHir1HrMurVtAKl3Zm5hQV0oSLy8c0zbm1T9JtFF+ccJU7uf6T/Bly/T0NlOeRPYY+b3VJlrfcovJonN8LD7aQHKSNi+x73bIyJDs8JftGGLX5pdcmOwH7PuUj
    neon-db-password: AgCnhC2ElobFv6/ThRd7Gv+xwovrwThbJ6L9LtyGQPDjrGXyqD78xzVdzSdDr6e/yGYz8Mcv29Uc9oGP3nUsJ72ZHXjtRghxHy4tsKfyDQ4vn3xtxX8cwqx4sWhkmS6Wm1VMNN7LxMqH6YtesraNVTRK8bd1rbSSvrR2EI/lSUO8ALy8rFGzrX9bunoQoPhJdpYyHYpboAfDBrWwWW4v59RsivNsk3qhN5iy5S/w99FVbt2h599rOxC0dou8E0hNSxVgKjU4zXWRgiuwi0cNAMwcXOOoJTsWLXK0pd6Qg2gIkO77Ce/C6vNx5fKXBjuOWsj6tCtcheCabGnp3p2D/zDi8Y0FAXFycRriJR0HxpdzPsNKuzupmq3100qAfHh0zG+lJKBZgFecIHQt99KNVGJ/PNXF4x4Lfuz4sfEA2KoxRVbQd7+DgMFuLoVpirClL6ZphQmu/xQYj+qlKAJ8TohJlH/WjAiZxI8K5lcrb/AehgKSTeFgXdTjf6QOuPrwGnHdX8cAicJJZf/3ONTvbJOibnV/H+3cVWqtYe4zL5rjBg5gy42d0oYYmWE3tCAeURy6j+1qlc/2cWsGp0kLnO6W9RcaaZtTepS9xoRozU86i1Qb8Zp7IBr8k9uYWfALicr/ZstXII6NgWhbDcfRhCVFCkdXfbk1l2rjbYqWgnjbWr1kHGPeVQK9Mb+Hrd3Aqi5mUMj+mELxvAdvegGiCD4b
  template:
    metadata:
      name: grafana-secret
      namespace: batchsender
