---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-b2-credentials
  namespace: batchsender
spec:
  encryptedData:
    access-key-id: AgBSWvsRYotLog7z7hR6gjYlz6Yh/P+v0zcXmhnafdAhcv3jA2INlK7oqxeVNIriYKRr5qLZWBB21QT5TYUVJEa7IZIltHUMxyGc2gWabp05y7hWILTpOHcDuC+PPGZz/48+UIK0fLAfgGK4kxtvqt1rTL/zXKSDurYfOj3sdL1fdwbUypX+WBjLGgqAp3b0n+NO41Naqb82M3hOFtqv0ETPZWx7sKqg0RkbP8ARKxpqs8RSgkclfB4Bi1+1ub/l0AUv3o7CbzyxfewO7uZGeZ8oor3/gYrexcefE8U9JzePfee26p61YvHGTbXF7scpfXNn5pXS0er+8W/nlB841poeX6grM5grb6wdPgs0qIbev74Yoh7wZWp9c9qBCUQ6tFACR6qzHcONzoMhIrChZNMIdO5eJCmRT7P+Bk8bVE65xjie+2NcKDKrD9KHHtRxof7vGtdWxPUp+EdWlM9hmlFEBcJFIVh8XwqXd4ZCmvqkDe3Ws9IRRK+R/NcZuQp9UHnGafcUyxWGqZv90ckrXn7BdOQHjrmkIsZ3td0pAaXnUpVZW4g4J+ndtAilKEH4L8sz0yxvsfFlF0RSvD8X34wwEbGdeIiVUVSX+NV5fxSrz8jcRl90m//5Z9VUoc0kudhpJVmG/elgSsk6ND6z2TuoYX/Dlp3lKIPlxJq04Pxbg0zUOyiKOP/wLmx5h6UxUX0g97yIhnFOHBUiHeMzy8p2XvNimKEz2FVT
    secret-access-key: AgDbnBKY4BGU0TwVl08xONc7Ye7amnirbJ92IMq68dr36VNnezzhh2kGVFIg5MCXP83DE4gXi7JTnN5pbt05kOPdSvs4j4O0AJXX5IIPS18UXDZV4a2ftbuPguNQdGvGKcBXVxLLF23BK0SveNa883/a3C2HQ47CjuPyS1tzrj6639hvyCae7CcVTwshN50wQs0ee3kLX9l3HEeicZ8NhidB1dq+w6b0E0cYFK/D3pW9zpn4Fa6hRThr0lm4YeG9bW/OnWLVg97rPG5+wXg4ZlUWupNJMRDMcVRVicgiY81NO+jbdoWiEnQDlZRLxgiey5oHtBj2Pcv2gXJtLfaBfv2Pu36YqLzyoASGdxxp5OrDvRP0yu82zL+zrL27iBNfxUat72KdVf95gci7aTUzpS9FNGd4oTh/vhspbVPU9v4bhyylKTwR+dJyvvc9myukaNyIOulmLbNGKuxqhDPgWi09xEWuI/0lOgaffvzOUIhZbxuZ9k5NDQ0kXTbMAFEcZi3t2h2qhne4VdMT92xKpJH+/HDPL38oRC60U3WHr2xNIVLkgG4dUJf30XFA+GUflu2Vh4RLiWpJBQ2JsWlV30fKztJOYi1Bb28shhqLvwKTHK99c5C43ecFIoteI3JDkO7lqvddsTFzP31F1laAo1ePIMN1ScM9rrQYr2K4kDIg7ndwnJWx+pwIn0C/NGOPqWqW1+B8yXh5wz2v6U/4EXL227B9iMr4MSJSGuODgiu1
  template:
    metadata:
      name: loki-b2-credentials
      namespace: batchsender
