---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-basic-auth
  namespace: batchsender
spec:
  encryptedData:
    users: AgBtdHB8fHfVsAG/xWTH24CdiipxAZFMv7xTJzESDcCTsieLbvRFCvZ5bAnTaDcYtp6+u8N5ZMF/Lkg0K5B89fBBOAJZXxfjCTNxbdDp6og/+D1OMxHqjavGXXbuohXDkQ3tLwQH6V4ZXgoi2psBAntj1yvEnUEj8hxuf2djoYWahzHAqO9YLlB1/taw/5UM6J8KQ1TmiagTyXE7ErxE2wwJGrzVlZUgQmdUrNmRbRvml0HmEsmfXqXn5OVLiCrWxpu9UNw+CBQ/KIpt84yEHPsYwyfJlFweR+MMw6W5YHiZ0iEo5RKVXHyaLbdnGi69+EW/X5KkR1z66RoKpctDyTAmLhr12eIE9vycpcUXoYzLC2SbXrGwey281JS7e7zX3/WEkj6nrB55wrP3c8ON4rLMVIwTHDTebPXgx1dANz20QKqCnxybBIIaEaz8jfWCVTtUjmCyl4yoDkUFH4RLcYIUVQVjXzLDDEg0kS8edfGwlzyPtVPV79YeDLdSD0ktA5kpGKyvcLqdpeIDbO17samvTqKlScBzM37TEBjGHBaz72iakSYB70tovA2rPMlM7/HHcr9tU0yrIw3sOXBfLY1LT0HaJ6bMggs2tBZ4bwWQSk3tZINsK347YtmhVkZlgZHwnPwkAn1jrzqc6gKye30lMxqwCtDbXfScerw9v0jqkZsulZbOzALRv97LrhX/K+J2t8/JStGiT45kfTttSUSPWIB68PU/oOqBW6xFYdq9GHBYcMsOMdebtykQ
  template:
    metadata:
      name: prometheus-basic-auth
      namespace: batchsender
