---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-basic-auth
  namespace: batchsender
spec:
  encryptedData:
    users: AgDPMrJj/fcKpe5jauzykXJC5anHy6fmUrbB9s+DpbVMIWmtC2yRPk29UnSHA2JDQrfXEkYzUimaW7qrC2T/VNpD8SpW0xDwJmUBAVjlLO8WI3nohfs4bk0kT8+j1vMP4KpUGqAPf5T/dbxtdexLguo2e6hSzRKOwkNrvDvd0XSQBduIWSEeQccqu5+UL8MvsqXvYagd8xX8Ibf0mPibpBPXOHIRrwpJq8TmDtNq+O0DSzzPKtKERmVS4ww8x+y6rroUfmPKIutNQH1/MmaOT2BRqgipa327uK1Jkij587N0vOLqKUI0H1B42KvmTHAwuoDBz1GMaAf2h8/EBlHdr/9mYIfhF8mDnMu/1R5rRSkt8ylhtmO+5bE7u3m0j45yryX5nIhhKwVOL8Gjh3j6nHEibbyubNEd9NvvojR9MStjBx0xaVcQSsToOteotnxfjye3H2ohW81gxQgpRiWW8Pk4EqCrGEVxpNK24IerotBtuT4SEiK83zWHF7PIRdt18RNFg4esuJGGQZqDF5xDljvPHfynREUO4gnUaDJHOy4gO3JonuT7sNQ5pFfcFfZ2CvcQRWOaDnmUoOGPAqD0GF1fcAYWvnK2mHjcnBY9mBIUQiVciAk9/nCUCxYBCtwtt+kcC2Hy/UKvOHglJkx51YKKMAbNCj/urOwWFr1qYYtlEj4nhYZJzNJqeLToKQgQDpbXf9XrcVkC+WjDVdaDR9nXTplp4dRoqmgT0FOVpQ==
  template:
    metadata:
      name: prometheus-basic-auth
      namespace: batchsender
