---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring
spec:
  encryptedData:
    users: AgCFumJ478Z5Uq7jNjCFMfU2amXP6bLM0QIkJzPlnJZU67E9YaQajJ9vcmqc2E8aTXcg3H9j/IdGALuP3SAq/PCXua/1kboI9n7JC6dS+4raLKrC9471aW0V8zeHrYceUdTQ76rreMLiA5tgeD+Q9YM+X+eOdRr0johTnE07G+YitOtoq0+hQ1pvPIKqca/HmOc50cTVdZ59ddgBVaQ0NgXm3F51MiFMivr/o9vYDdbHkGi2jcioR2lHPfX+NjKpD+GgFkmnwOjQwWlz41cW+CDgtD84C/cHJj21aubHGPzbb71EFOD53q1rOyau1IHnz1Xl+SIk15ItBaKolETnJnTeGrpTbl07KwNeuqUHnYkzikeskAnvj06BBpC8mE0N/BrHtp13a/5FRqSgCiJT3ar9/j60DiVGVQFAKmlxEI4vUbeD3vC5fTy2raprmcn5aLesP2+no8VEm2sjzpWuqruV+BBqUBCJytqdWasL3xmopY2HcSs7UQMgItaCneCezZi7JedcfXNdIkG0AA08DMb0xW+aYCN5frv97d0HVy6NcJX6vu8wYVfukhanmusDtoRjW/WosDnDg9KMjhs/8mae+T3hHRChb1DiN7sm8tSMJMk+XriZqbtsr7BcEE+3rV6wRGg2jcYy8wL9NIqiaEv9chhqd6w0/pkhtD5lCoz/stZpIbXjeo2QE/hexc186FQcQFaX6VHq6lYDYVqtpmetqkmcgygS0UVKV/KJysyzXKU4WAHVDnia9wP/
  template:
    metadata:
      name: prometheus-basic-auth
      namespace: monitoring
