---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-b2-credentials
  namespace: monitoring
spec:
  encryptedData:
    access-key-id: AgAPLH0p+w1tUFR98KLftYqx9P9k4EcUmYqMLWrQhBurlvHLjhyNdbslo8aOovxowPuuaGLygPkCf1wZyq/9McNtjZHEVsQSOFG5Lwe6MS6OPZwoMLNQmBb3VgVUGxXSlZHZKJcgddMwGSKiUtSy0VLGqOc3UVzoxaCOdhY0r2eawKKOgQq5g8Xo6NcV2EA5VZQD4HSNOBBbEsiimD59ZVMMcbmgGtF/cB71rz3AfbcrukdgS401syoAdpISeSvjnamPPGbY7Lvw6Urn9rgYloTzcVwy4V1e5usY96wYkt2f9jwq4nho1kXbWDaOwMODFKvTfFs00zSvM5WdHU4J6Z5VE9D/Kc0AAxY9ugjR5NSnrsPsgMv98ZOxXChafY6nS+W1N14VWuQ1wlcP5S5dZNHLo6lX4L5XG7REYm1JSZGZIco2P75CO+0JzpFTTC+3ID9xu6G6nebcWIzhlcjzPo3rreOzcCRN+zm28Rn+d//sheBol0bQt4mhvt9ZmlFCKKpso8KNjMCiVPgKnRMKDZQLy8tXRMJ5picTDkwCmLwjtkNGyebbe1SmV/TIN2IAY0I/DlFEb/SSlBNaodnzUhX97fmHFz99aCoikSCVp66U4cHDcvG3j50LDf1roiro9eDjnHzGLKWiVTarDceXcZBq0bAPlC1sN0wAgq3qSUoeho5Hcbm0/Z1oIXj1Rms3AsBJaxeZACa1xefLt3XxjvK3+qK1A5RLCbJL
    secret-access-key: AgB/BJC9sSsyu0eZGxfQkl17UmoVxCEc/jU/2fU/Qwt5FIb9zbnwSYza+ZwxNfDYNqdpb77OHo1WzTMqmCzhKtXoNgOoR5BxN9ILl4UkCk5hX4CcAYyCa587vzmbfthTBMB3kodEP6Mx+J/5zSNMJ0fuMS4J4jy3f1lgUolqijeDhWADTqFAbE4mU78Tmnmalf7+7IMemP7Hg/R14fjzekhHRYuPSeZM8AEZVibPPHLNO2EG1wSkokLuZk3UF1dgj6sP6QbHs5gU3K0tGj08pXyaaHW/6jaINipyGpII7ODBP/Tew8f79hsg67Zi7MabxCR6YH7T3gd5wrsaiWQor76cEKv7R8oLQ26CfwJqCHrgpLsA0bj65G+c5g7hg9jQZQVeosGVCslEZ8TAZ+5Mpmmf/4WRNlYV84YucyKedhrdLumpD4utd36YESWv4qRXj1oyuAJfvvTw511F6Au9WRY44Ac/zqOoirVxEy7dg41Yf4fE7DBgvNbKglQejbCz9iravtqgYlZZ9IMOQ185fpTQkTdujp/oLwniyyTeVhwoCCpxAU+jOLNRua+0mOsPLmF889rgp3fUS8lE6xMn2ccpxhQZtMXJSNaedVN0/E6LB1+WKFk4HBPLYTqI1bczykbWVDh8SHlQCJzWDGDLcI/nrCoqVlAUP1tNIfZMenlPWzp/YcV2bFGtS3uZ+av96qlvgXhgYgE5FwzPeVRlce1jfzQv0AR7SphEK4o2+UAL
  template:
    metadata:
      name: loki-b2-credentials
      namespace: monitoring
