---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-b2-credentials
  namespace: batchsender
spec:
  encryptedData:
    access-key-id: AgAQs3tHJYnt+kZZUtVmC4uJtWRxlFJPlWFRA63rEAYjwmDZzqNJrDi4F+hp2QkhipKpFtptt2CekBiYXZjEvpzBqOvzfM9Ln3aoq7tHh/CkowUABXwh1uzSELISuI5SUnNdHH8PvZSEmZrwfTjPyAzU1P8KsXf44qZ7k6JxXfwsBcJCnmRQxYm6XT36kzJA+mKGMS1bsLOt5AiFRSotfv3/jqInNhhqPSMBF9TDioxhskysvVoppgyk0+pQK5bLyFxlTr6Qt4TfiQG6InXZCoPwpVcQikdxErA3qWaCsbLQvu6jNOKJN1vdr8BU7/oyysCS2UUxHsG/zt1D95vnzyzJ5QF5r9axLQfaoxV1pPJR/iAx8D2OwonGIuCauEdHQTopCjZzQNuFlKGUZlZvp/jc6Y5PgnpspQwqnByVt8qaLqKbEW8/u+gs0GrWAh99GeSSgZ2ERPrQfNSOVtE1zmR5AcYVgykOK9O70HwUIiglwHiRQuSsIVeJh8Hyb/Eg0Hz5jBEbMPvGDzADOgP0TOxkZ5xqkrZRof7WlrIHgfDXnlezK8FqZsNKjDvnxn7ZvUR3ZKAnhcXWvARDS+/V/6PG3cGcspO0qYY6Lpm7UnV0tEU3tXmy/mPBHROAmStccdfXyXCgwUbBex9IBm9fBJzkOwoRgIMjIyPHiBC+mESdVTTzeU3c2XgHBl8cBCuZxF9jQNDkc6w07zPrWTFXqlNTyMbgWBm0HzOe
    secret-access-key: AgA5gQTl2FTVzFBnZZJnOgwXQOGBoHOemfNSiS/77zxX7sfoiXekbP/nv1tQKbVI6OVHFQengyV+TK93qZ+gk2IXMQ697Wnh1a/kXXl29SzquPl/P6/6keux+xLcEL4SbNrAdJkNV6AYUuw+igdWx6Fs3o8y1SzZAB2KkxOsU+RvWTzd3z63Di3mkoRF3d2WYfZ7sKpE0HARnPAb8Yc4d++l2k+Jsdo42muyIfTkoF0s8Z4aemDczsQ3CuVtQkzt0JvTyLBfikeHdiiBvVoGFNrywBfm6NZKwuhyuewCWCCMYcD58mo2A75bHrRGOkI/2YT4XbWqITc4GP5uAJJi5kRqAOX28qz+ym+yaiMRjl/ezLkJHQekbFMwd3d24ShQVMm0jGicCYhZe19gU3gA9NyBcAb1F1FAnDL1SUuj6th/sbsbf9oLJXl0B9MqHF9AglC4FfsMXe62G+RweiCcn14LsMchVrot5ZA/oQvoQmY6yrbqmhwPDEWuZzhyMZvbTfaXD5vGsy156nxe0fR9OS2OHIAaUlISrNEBO2RT5A9u2cRKiF38kS9Pfk6UX65dx5R1yNsnrjalPGMd0+/hKyH05ty9fB5N0m8CkBGv0a0NASUglLwLQ88MfR+e9bu0bBJR+wng1Jl+MtPqZxmfX9DnEpiZNT2UYHU86kF0meKHfQkBGVVN3LYrNCjUJaS5saUbxSR6spjkvkwHqDrELrX7H+tVHZHspTdwcUlUluSv
  template:
    metadata:
      name: loki-b2-credentials
      namespace: batchsender
