---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: batchsender
spec:
  encryptedData:
    admin-password: AgAvYlzp9YbjiK7Yj0RCA1Z+mp0AWCgQOqGkcvpydF2sZW6P6LtbpnDLR2VbyOylRUxGRpETz8udid9rHIGfmAvtWw43ctuEaGu+keIgS3hw0Cl/QMt07yMNrrt8lvFza/9Z1ByCxXFaB8OnAWRvi9IHEPj3TdP7SsEt1ALRpkLwEVRkowHd19I5nSVxae3NaYSlflWReiReboR2EKcXBJF/xheeM62WzwbiI9NLsbVKQHMGHPVhLpfRKgK1T3PuuPKVnkd+M0sThyis0JKKES+XtTRG6q6rM9PScRac7xATsrDjReAIvxxA26hLJdCuVP+afyno3w6p8+Dch35lO4Piyq2O2EVTnyS/Ls6XIYdGonWKUcF0WJpnIJglhwpFQT3PbqB96mz/zndWXd7eb9pRUGMAhX27V438F6EeKZsgvnxN+3ajreRDzgVo4EhniHfunZXkduTvpksooR+7m+ygtv5VXWuOQlDYNWNgoLBjKdobmM2urbCzKnL6hO9DtYxB8CDLGDbHWSQSoE5q46yH+zrDX5h4B0KxDOaKlGJSWQ9D5E2ZHoucB6ndkoxbZ7u1WPBLof6LZHaFyBVjYU3dgWUf6/RnC8F4nAjxj7q17pE9h9mdGzjDENtLkYRfe4Fx5WFnGt3wQgjC4F4SGCFyrm9u8YqH6IMH00EB4nY4SqAXBck1ku+8C0JV6uS6YHbPxheCRWwPBQ5lA2PpWqlTTIw8j1Sqca8qxn2N2huJDDG6ifbuSC5xQKu7
  template:
    metadata:
      name: grafana-secret
      namespace: batchsender
