---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-b2-credentials
  namespace: monitoring
spec:
  encryptedData:
    access-key-id: AgAV9RS93QxlOgz6QC8XO/b9rZGcmRu8V69fGZ2FjYjn8XkrD/TsHDbRwsCs2QGrCfUDUCmNGaHo6mjXgWGFlXF4BMbcqJcB5IP9yLYTcZ7Ba/flcI3y6xh7QUhHgbNlO4KzyfsKGeTzdZ7cnq/dsCg5kLDodkMsNaP7wsLvWTzvav49kou2lnq10k8Y85s/dSpV1wOerT3iscIgwuAZ5RwQveAmrGimVm31pWUiNhz5A89IVQnrQK17/5ukbojWtG91s+6rhNl0dywhJKNYJMHw5HW4tFlung7ft1m6sW+bNE3GmErPd6z+S75gQYzuOZwuI/BGTIyeQF9WPzvjqKh24s/vzJ/0r0b/arfR+yw8hedOA+ydwwbPgEUv2CdB/slBCJbip9eS3gYPd6iZHa3wGgWeDMagjm7UwPn2WFqPswTOGWO3wL3XMxmjpNkC5wJEJf3ivl75gBzOhWDNJGAz9JxFZOVesRGj76ZqFdYRFd1ir6rbWsqKN4kl8leegY0k1wIUUDRIOC4bvKgtNJhwRVfddzAFAxvkpnoKni9pyA93ZqrHWKPTq2MkF1YS5Tlgik9G56IGJnYSjM0PTr0jtQ7QfUUHXvrqvbnMZOGSM8yYkltUsdgMvJ+d9i3oNHm6Y+t8laQsWXNr0FYJT4qggRqA9lGGglxY5epQScdl3Mos9s7MOqSTSy7bk4JyTkSJuiz9IYHfHmcJjB3Crgl0DF8kSxyfvD00
    secret-access-key: AgDEZLAzjTvztF39Dm89mBCo1g2z6zcJ41Uvpg3M0lnfQ7ffY01KdpADs5jzjQhJmmxsQk23/3vSjnf1TMa6fMQ0er6WKiVo1DwwcnxatN4KHnrpT/4a7kFrmerp/+G5s90IARWbW0NoskuIHhVYzfakYnKVg3EGDFh+we+6Iv9uXBkGawl2/gPYatrA6OaDyZPq7uRXJ0CM66ma3y52RMRL0dz2Trd8Ys9ICrWkX131yCv14TupLXfgYDTlvWRvDLGaR3B/Bt427tTSfEA9Gh0uEYZk2bqCQdU6pS52wAckm/aFsRE9NxrY5LPQLv5/pcPO9BrzyNKGH/8SCxHaP4GLqlwg2ZtEH3s4SmnvdrapiYTtMC+RinYIKQHzWr/gh5U+TcHA22N/7jpuOQhaEDNgIT5MzcZz50qUN+BbWvnJ37Ihr7hauFuR0JauCHifzvKlCmB6vdyhg/Evh/38WO2ZCW8Ibys3txZ1yhTJtIlULQljdujAfoAykYLsnoK+ji1EoHKor3S1PjxHmuP0By7zAoW/HMOe3K4OYrRnSaXhdD1FuhZxOZAS9GY9Xv/pziA9h+Zl82MoLmKckKVrnHmwv4OnBFPlzwli/zfk6H/9ubyhNXPAWQ7sAxeQICFv4GIP/rBLwXeEHd4rhdRApmVPzCV3n3JOXF2BJtFoXtGKOo+LSTaFcsXET5kCcgwix1QGNn5OsREE/AL1LXV9aZpzw5P85Gc1hAD8Uw+/Rkrl
  template:
    metadata:
      name: loki-b2-credentials
      namespace: monitoring
