---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: batchsender
spec:
  encryptedData:
    admin-password: AgAYuNNj1gjz1ogN2Wv+XgXNgYv9cR02O5zdwSZPouJFbRV0e6Znw4cGstbUfv/k9bdTDmPVZLJi4aKVE354T+FKF2OKQBiLwwI7eqc2Dlp4ladczrkAowXC0nuPmAOSpXkt+WPzwENTZWRbER56loWgHH1tJbv6vpC/ie62IO9y8WwhOcqtT39/XH9j3KTuXCQbjDutqClrP//SONgQDRlAvbUd/T/6VimFpf/c5aX99mEEl6ffpuzSERGQVCokprW8YguIvvSZOm+HiVjy45xRlJc3lS8Q/POiFGHb6AVo/xmrUNHoo/VRvZtDqS/VZNnyVYaDgtSc5apCJ59dCzQPcI8bhX9xDEpVDa8JQLV0SrYZ9NpN5sbi/D+Bl7+uIS/gN/LzesHOjVLZX3J0GuXbz5hHrAvlxG5OZxFgc8IiJeZMDUx5qG5YdgVK7RhFvs+VQIYH+FNjK6f4Tz3gdMjIsKj/IIMleOxbO/ioqkeDhQZ9pukqf2udPat2IwofDUdoZMUaTSnOJGL99Y8hggUUiavou+4zX/ewFAY4fWUSzLqJ1u8kx+EtgZobVjVNZNCf233gMzabZy6fzMyKovKjuTGYUWuZH1iSib3tXXKMqMtBdWMlPvrjcz43WT8GAK8S9ghe71At8ZjheClM+uoHg+nPMePDsf8ElSz6RxW9lbIN97gZ22WkFvDLph3OZlKLDFsnfvU1ZIKoABuwWKCjkbAsU27v2goFL3vDHBzNwmw0pptbghhma1uD
  template:
    metadata:
      name: grafana-secret
      namespace: batchsender
