---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-basic-auth
  namespace: batchsender
spec:
  encryptedData:
    users: AgC9XNdxw1a9crJ5YC79/1LHJo89rikTTi/ls7/YuNM5NAcTljI7SIfbKnzAlgBqYcNmjGa9rpiMzyM6GpP/gjAQP1SjgoqhclXWkHIovO6/Hb4QZu6pZG+g0ubpNgR8FuFFyafk+saUUcMxCvRbzLgNvgl6IjeopdKJl+0HQruZbalF49Ils6Ku4pLCwaM232O5FpJ0IUKh9YxUekmQN7CG1VAtBYzahgGUqejPxBHE73WWK/3sBel5gVmcTZ7N9Y6IEJveNgTTgOSx2dCG3/hjFhwZtnPlbOeiEJVtDycxvqSsCsqGTTJPw0F0OEi+Hj9pCv6XqwsZDCEEJrbVf06ktdysc/1HfM6+qto6H8DF6ApiCHFTo6vcMVOHAJNcQguP5/JcGGDSl8IfT1RP0aBKg2k+dyIzIaV/KvGZZjubf6I+QcRR59oZBAz2494CsjZRi38f+61T33yCbQxbhz8qbkIAGBcFBrvnXCpMiB83/A9CP6JlYU4yLUzPwBfUVvSmhOhZdiDeWnBO80NvDCiwDWbzRdihGTt0prQFxg9nXOGbUK6JuLxCisnq9uCgY8R3rGRMTATrbTIv4SaqK5be6gPfK7TZKF/iCQx27qIOWAEBqS60OuUhObY2dtTZg4tZ1fjzzkQHorFP5aQZEcInCfvHnPih+8lC5LRB4icpq5AlVGqVdGhVg1JyC9LhB9udgYSD9pxPUT/iNg5ffHOSmIRS46eZArQzXF1PCxFVcbiS3QjyvBb5CymM
  template:
    metadata:
      name: prometheus-basic-auth
      namespace: batchsender
