---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring
spec:
  encryptedData:
    users: AgDT+R26rWq2qyp481uL8jv+/NOiuwd6+Qx1nL5qKc8n2GbUj7xsGOzlO18YWWvwi9NWpfqaKoY1Co9TR/U/CmDVt9U8Pk7MNLfGv7IHKOmpSF3kNo77VJno3JGRdhK3Bl8dZccXpaTXl6FcumLeQlwQcsVr+jd6VJU3rfPscJFzrzS20InPz5BMT692lkDUpMjTD0/42GFC60BRy3fxhA6LBcloAo8pCMDxtgeAVVpyq9oodjF+tL3fJzKmlGY1UKB1EiNmI6Q7AQ7KyNPcZFx13kHr1pKw5kYbNY1rAKumFMOxsdfzItj00lPZqr+kbFw5U436sIy9ZJLZFJjxq8I8L5YNjoXpuZmeCEL3EPd/YkNLmMhz7IVkCBiEtf/0mSFnWDjls13JI5QhfcjTM4cA9qefZq/UCFi1er6IoUvWjAnUHamTpVvUu1FwSnvkygg+zsQ9zbUfVSlzR5R/+IC5nvDqlc5e4eCdEE9iLGBDTYE1Hry0PiDfJIodJh/HTlwm6+pb8BCujsYMCjxzAqF5GuXgirc0EafE2Ee9+fBkdu2siC1FxREJ9VlclpuljW3rrrJgQDQUttctCYNI1b00TVTWG6E8bsU4s5hz0HQGMMLopU3A7W9NoM5IKIsU4hTu2ftt5l4pL2ynByN4cSQs70zAjTsfD8dOWxOUHVjkY8JYAKSDKifbuegbNRqjVR7FjPgOPbe8cpEnRruAb7jlNyrM9FqjT7J7IVBU5W9zt9cMeLyVLuJW+eC1
  template:
    metadata:
      name: prometheus-basic-auth
      namespace: monitoring
