---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-b2-credentials
  namespace: monitoring
spec:
  encryptedData:
    access-key-id: AgA8utKHgE/M0KfcYmicxjpjh5c/86O7r/BRqFZvuz5j3o0CP18FOtWTYDTmRja3igp6Bd37PCCAKjGfv9Xg9BstYRaE1VqjbqxIbJks6gZjhZWPaoC40BuNF24wpbhFm5j50jxxyFFnCyf2ssnmULkwQ//fgYOGv//iFkHPMble7iS+jvycCbnC/yV0ufzf6atNJMQQWNwPhZTFCSZ9v4pei9ZFBSEaZ50TaoqUpcJwzfENZdiLzqi/0DYzO/8QA1bNi4OEFLYs4Km4wb0vmmAVCZWXbGNALDoespd7McnIzWx0CldqpVuE6ZpddpAnzjPBoJfdkTJBe5QnnuXsYddKKTEsPStE6EC9DAeaEwX5lF6GuQxmSixPbkpRhMqIbp3aYpT3+TsUCXbWiNs7F2zJwux+nc8CkKLOJRmMVvZuOVXBRefv81LWwX9Gn1P/F23PYLoCMKEedyo0SrbBFZ3Yw1iXOXB6jLFpCr/rd+WDIDtSLiOcOYp2Wb90FRnawJ47EP0iA060lJpEYEa6sTW/GmzjgbdE5SDUFNLMkixF1FGiLZ+CsV5HPm22vse4SOBsNEuQYTac+lgFuQ4EsudxKDJdMeX10z0YGHt1XB9aoTw8eHBwPZkQt5z6Iunust90vE9107/J3HmHI/DMGZ7ofGWltVacJtE8Hr7B/BP+Xlqv+WdTzIjv9tUTaHKINHdh6+l+gPw9uk277QdqVyowoKG7j9+JuHDu
    secret-access-key: AgDaUd/g9AAy+vUG+l8uVxNf567hMfx1aDRjYd/aXYI4y9WCCcp7JoKOIt6mhmk43mu4m9T9g2zpQ8jhCs18/W/WI9iEPxzgmjfEwgh8eLf+JAVFAX8h7w2i/nKyWkNHYrG01n0iLRk23X/Hf10B7ydUDggddShtaIqjkLu62+1QKZd/uVY+CazNVdInQprU1iH9EJewMtvFvdcZ8Q4WmutKld7faYQ1AJBbHYgxZ3Y4mZE3pjS5utjfkWUdkWWqmb5LexzpQ59wSzQlitBP0mELH2kFTCZMpZTKjns/7lbARJCUaxdV3UmUPD5OjOXCN/pdqpPw4z0mN+1rWMpRqF2iEGnnxeOMuN922B6oqXBo0vXC0x2wEfGpUbwQjSWvRAnx9W8O6f1RBkEagx1BKRiGUN56bqcpngGpQxsq4YM5uoXodjueNBhHmH/86Tfp3InCGU7ImznEjGROCP3SjGLVKCBYjoZefGjhyTxdgvCxrXhhT+luTiNLP9UPN1zwvJYL4M4wzXLq1nJD3RH6IGjcNC2W/35qNTrYpfl3t4N2WnPzoyFt0fHt7j6RvhxjgH6kBu4AwxEz/LSx9b5RWxwnBLGjtLkBXu6mCAXIVdnPBNRI9gPIclAHL8/DgE30y5gnURxGyuc5CFUTkvT2WrzdQ5lD29kzbV7f5ShMpz9oyxCjeXSpLvXSQYxiJuQjMexI3piV21K2Ayn3jbO5FnSvaC7AC0ACAkGxFk8EakA8
  template:
    metadata:
      name: loki-b2-credentials
      namespace: monitoring
