---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-basic-auth
  namespace: batchsender
spec:
  encryptedData:
    users: AgBgpEdcK4TnXsZLLGHMww8MnexFn7BH+bqEZHuvvO4N76+vJS2nTWJHUcJsQ5LN6+eYuU8nDK7vjqhQ8Gcqj84kknu8s9UnEb6ISxn40N9ObFEUFzgeLl2emMDBAm2liUNNYmxxfot0UB6iVLI/Db0Iu/tAZTRIzS4JzkJ+PU4Vht/du96hAFgkQgjFioI+DbFzA2RvZT1geOi9U9ESy+YUKfio9Kv7XD0yRhiYI+vGXawrHUApNU7qnsCX+aq11CM5oLE83Kq1jy3wq3BN5hApLYM/Jl9/N824/pwf9m2xqFM4/wHhVdQbXtWlImXpFPkRtXnmlc5GgquoxDo0AXKHQOiF55Dp4PHxSp09Qb/a60WGBlkNrDLVDysIWWtQbVfgkeWKWsf5deZlgW3wTIh5ejVZwXhiYelGmkWBATP8i/XeYAcY7cuO7tViaWEboMFbb7THXDl0YwU/ny2B8w7C1rMyK8ZpElkbTrIooFsRABetFIxG4badLRjx1FwY8pQjkCeVe5npd1cJprXuIS5U9xsVPvPHOOJgY4ywgcfsWGIrtvG5zrL4bLQoU1CIP3ydPr+YMEFcMyf6qogbgXC6wbTZRFuYMGFHwQuNYVDtpWWuclg9Vtn6J/+bYiaoaV/RfQkIlFbdlTzxTnoO7q+nT8XIaA5g6zvbIFMJM/DaXFPuSyv0JHv/MdWvTAXul3cBG2ElgbANEgqH1NsVY3i+Mxs4scQgOZ5JfTjPiRCA8/oZ0/wryxaxt4BQ
  template:
    metadata:
      name: prometheus-basic-auth
      namespace: batchsender
