---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: batchsender
spec:
  encryptedData:
    admin-password: AgDH1EXvFjE9fMaTSr8g8zWWjlj84D5UXrC4LgQjPCzpx8mJm91R6H5h9UhNtW0nyMT1WW3FFuiICWxiUILx7PWi/HBRfXDea0/lkBSjho3U4ocx/1Osu5yQ3YvID4p7TkwhuICjjmDkjpnOPhcC7BVloyMMMuiTxmFFs1XxAwmHQAQpY0QonZAhI8epIC5JQ6FZbyR7+fX5X7LACL7UJp94lrgmoMEVXSndEiBame/x7st/fYGFWuvQRqSQ2BLxlAPEMfjnqFOSzmxJ5RBRmdRaI2EWf04BQspT5VD+j/EAP5c9BExXUv714ytmX83V/1MrW4DxKRnobJ5+fJ6bbXskYJ4IChlmDz+HibaKkpMZV4Ovg4Wnvvvv48vDVeD8E9IXMwmmMbEd0vUXaQfI3CLZg3Gk3y0xgbojy+H2ETFwvoCtaiyBPJJRGDjzGg5WUS1Hb18SECgZ470L9QkBVJwknUCqVsGAmiywQcOGCzT27lxikX3EVwj6b8BgqWj5VReoFbYJF4oJUuEsZnwS7ruhUvvrCi87YJ8pUiIPqtgRq36Him3xuLkCWRsq9D5MTkX0Zh9r9lqw1e0ioQZq156YZQcS3rMYcjBeXLUWvxZHUUzqRXBhqXI7NP6LSCCs1FKn7xdYWwZ9Ssu+025e50Xxx6JqIzkaGf1XK6lRhrT7i6qcp2wuH5IWp8tpLMT8kqsipX1snqMiWJbsF6RHjL5rzp3TlvmM90mbSvFi0OcuMrMqn+S74sPdur8m
    neon-db-password: AgDM5iHEoV+qhEsHrTTdZu6HZMCqMNAcSEPDkDZNBqZrAnKqnO55CQKEPhUivCH9+trOxuVkf1PvLr8CIvt9owQI741r1UHMfL5bRdvgcWcc9u2/t0E8A1RjrzdhM6oA0thzvQudRkw1OgJxnUnu4aNY462toErZOw37z3AGfZ3PrXck4vNiHG1KqS/Eqj0Gvl7Ya+Uzm4eJAVl45kfKj19z9rPnySCCwblTqkpMNAtu2zdgoAQbuc7dHVtFJ/2lpafGXT7ClH0fa6T35E3PxoKLZIyJ/rempkSBxDeVUB+c3t1Ml2K96nhfsOWNns0D0uZ/qKkGpYX42ZBEGbHGntzDYpl8WwJd7OeF/GM4EUKkoFPoUr/EzC5yqtcimOiQ6tsRRBDO6NIO2UPF8DpXxbJdzuzkaS6rL/nFU0Piv0Ys7UDxqc+r7U2ctTqWYaxkr+HNaA0h4HOunk4AaXN1NTQkp9amkoq5If/sPZjsmUEb2G+SnnQHgfolRYUHexuoQHJaM0TPe8I4HDlMG5rcKMngoGEe8oX6c9UzQSB6Wdv1CvuWkjpKyVjzmszswfoO3OPNDhLOl3HBux4D+1THIqhXITd3LG5B5PTRvGyFquFwy86njxMw0GS0Wv0qAUNtHhH2yeqWQe1vu0oAGb5ReiG/uVBx5VmfspM4eZNI9b5GD3TFTxL2IuhBxjrYOrvJU0fowfyHYhi2PB6iA1ZlLvKt
  template:
    metadata:
      name: grafana-secret
      namespace: batchsender
