---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring
spec:
  encryptedData:
    users: AgAerztTWpsgzm8sll7Ype/7m1DWGtk0Iz1tV0I0KZSVxieJ8R4q6LOETOioF6qlVMHW1HE0YqVEb+05N5MIyEbIiryGvPQifSTmR08AEMh5IMimRTZwDen9j+lF3fRIbZdoL/SG1LVe+BTiPCtgWhwWWPS4FwpWSec0M6o4LQ7WG8TXDieDpw0EtUqvex2DwUAmTcjPoZU8B82bmBubiSUqYPFP8TP55F8ppziKPOXT6gJ6FMIdUzT4R3bxjl2j7hMc7O7hK8HYipvLvYxKF5tvFCZMXsYizJSli/7Bmba4Rg53tuiYzGfQ+LLnhDKbJfsrrlZUm40kKkiwGSvDfiNt2CSQzBcSdNrBavxihjOsTHJXRH8kDSZM72kZPW0j8K6ieSTlkpRWP74uobbTn1TCIQEzzPpZ6oRSQbF6BxWxoalz/zC4ycaW1EL1QUOhqWqg+SKidu3r4SfuMdZzXWle7IcabDoBrIoytJxNu+T1j6amZKB4xO07eJXO0AHc64hIjXDkWnX3U/DI3U5ONd6xUx1hwZzoVnb01W9UQwPGMSoZQ9QqDa/z9jjjQCgaVcYkyo+M1t0YUl9szluOKXDEW5APuFZfwxIkZF0K9jx8oK9cwkYJF+q1uOAVyMum3cV4mt0rmrqslMc/JsAezuqLGB2H3Z87R98CywkiSf5xfGBJAfsVXY/nK3sv1AOfEwSaBlDyTB677vNJozDtmF15LHs9XDtQXKXkV4+YiRQrmweVUmZsNA/sNUtw
  template:
    metadata:
      name: prometheus-basic-auth
      namespace: monitoring
