---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: batchsender
spec:
  encryptedData:
    admin-password: AgDcMHOqN7zMCAGOeIVGachvsARJfB5oNJC5Lzk+fgo1y7r6ESTrVVFOYEpzNBOIynoOHH43CCI7peCnxS5vrxwgwXtjTH6i6wpS0UAQBMW8Jgxr2pqzCnyHT4En45V11JWDKm1fH6MFmqh/8jPSFM15UVU3W2TZMf67cHQwsMtcfmiyF3GLl1Ihv3W4JSmlJJNXW4zdCGet8fd/EbJQnlerp0J+w8fklx4cKViuylV0/S3uU3VWXd1SIgAW/IG0R+cI2u7/szSSXIKC3FNYiUo3dX2WNHJVf59RA3YPozsGt3l+KR5mefmUEZPiQO4s5xB3BiSi1nBt8fvew0b4SAAYZOcbiuoNbZw8AhBDpGUx5Zc8n7OJ4Ny/J+HlMo7ThSCMMDELGNFIYAfztIyswPm234gAXolDadBpIpKTlEIJXO5zLV1TwIr6rqXTFTLGpBik2ZtBUOtTRF3fPEIuNA6rKp+Uq1h3ZhMBnOM1tU/67lBXCNskIiY7WYj8wGnBm9Qek70a6+bjrLv+sVPIIOiAN+ZzhLnhIBPV+3haksB+7XgDQndl6G9QgAZoBvZlRVOlzh6WrPlUfPUZmqqrDlaKZRkXFG0jBKwtaOo67iu/eC67xGbYzePuCxei6KNw2E76xR4bksqJiV76HmE6RCuXXyYSumeLuw/JDAMaDnqyegg3WeHxZQX9LgbMkrJ+kXphUsYJ7EpKBb/23C86FWsG88e1NxCxYYy9NVk+NTgHFdvZkzXgFAlz18Xr
  template:
    metadata:
      name: grafana-secret
      namespace: batchsender
