apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: worker-secrets
  namespace: batchsender
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: github-secrets
    kind: SecretStore
  target:
    name: worker-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL
    - secretKey: RESEND_API_KEY
      remoteRef:
        key: RESEND_API_KEY
    - secretKey: WEBHOOK_SECRET
      remoteRef:
        key: WEBHOOK_SECRET
    - secretKey: CLICKHOUSE_PASSWORD
      remoteRef:
        key: CLICKHOUSE_PASSWORD