apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clickhouse-credentials
  namespace: batchsender
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: github-secrets
    kind: SecretStore
  target:
    name: clickhouse-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: CLICKHOUSE_PASSWORD
    - secretKey: user
      remoteRef:
        key: CLICKHOUSE_USER
    - secretKey: database
      remoteRef:
        key: CLICKHOUSE_DATABASE