apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clickhouse-ingress
  namespace: batchsender
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - clickhouse.valuekeys.io
    secretName: clickhouse-tls
  rules:
  - host: clickhouse.valuekeys.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: clickhouse
            port:
              number: 8123
