apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres
    url: ep-raspy-hat-ahcdzwko-pooler.c-3.us-east-1.aws.neon.tech:5432
    database: neondb
    user: neondb_owner
    secureJsonData:
      password: $__env{NEON_DB_PASSWORD}
    jsonData:
      sslmode: require
      postgresVersion: 1600
    editable: false
