apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: batchsender

resources:
  - certificate.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app: nats
  component: messaging