apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web-secrets
  namespace: batchsender
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: github-secrets
    kind: SecretStore
  target:
    name: web-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: DATABASE_URL
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: NEXTAUTH_SECRET