---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: web-secrets
  namespace: batchsender
spec:
  encryptedData:
    DATABASE_URL: PLACEHOLDER_WILL_BE_GENERATED
    NEXTAUTH_SECRET: PLACEHOLDER_WILL_BE_GENERATED
  template:
    metadata:
      name: web-secrets
      namespace: batchsender
